from celery import Celery
from app.db import SessionLocal
from app.models import Order
from app.services import generate_facts, generate_movies, generate_songs, generate_prices
from app.utils import get_date_formatted
from PIL import Image
import qrcode
from weasyprint import HTML
from jinja2 import Template
import os

celery = Celery(__name__, broker="redis://redis:6379/0")

OUTPUT_DIR = os.getenv("REPORT_DIR") if os.getenv("REPORT_DIR") else "/storage/reports"
os.makedirs(OUTPUT_DIR, exist_ok=True)

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>EDA Archive Report</title>

<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&family=Libre+Baskerville&display=swap" rel="stylesheet">

<style>
body {
    margin: 0;
    background: #f4ecd8;
    font-family: 'Libre Baskerville', serif;
    color: #111;
}

.page {
    width: 800px;
    margin: 40px auto;
    padding: 40px;
    background: #fdf6e3;
    box-shadow: 0 0 10px rgba(0,0,0,0.3);
}

/* Header */
.header {
    text-align: center;
    border-bottom: 2px solid black;
    margin-bottom: 20px;
}

.title {
    font-family: 'Playfair Display', serif;
    font-size: 48px;
    letter-spacing: 2px;
    font-weight: bold;
}

.subtitle {
    font-size: 14px;
    margin-top: 5px;
}

/* Layout */
.content {
    display: grid;
    grid-template-columns: 1fr 1fr;
    grid-gap: 20px;
}

/* Sections */
.section {
    text-align: justify;
}

.section h2 {
    font-family: 'Playfair Display', serif;
    border-bottom: 1px solid black;
    padding-bottom: 5px;
    margin-bottom: 10px;
}

/* Center image */
.photo {
    grid-column: span 2;
    text-align: center;
    margin: 20px 0;
}

.photo img {
    width: 100%;
    max-height: 300px;
    object-fit: cover;
    border: 1px solid black;
}

/* Columns text */
ul {
    padding-left: 20px;
}

/* Footer */
.footer {
    margin-top: 30px;
    border-top: 1px solid black;
    padding-top: 10px;
    font-size: 12px;
    text-align: center;
}
</style>
</head>

<body>

<div class="page">

    <div class="header">
        <div class="title">EDA ARCHIVE</div>
        <div class="subtitle">Historical Report — {{date}} — {{location}}</div>
    </div>

    <div class="photo">
        <img src="{{image}}" alt="User Photo">
    </div>

    <div class="content">

        <!-- FACTS -->
        <div class="section">
            <h2>Major Events</h2>
            <ul>
                {% for fact in facts %}
                <li>{{ fact["title"] }} {{ fact["description"] }}</li>
                {% endfor %}
            </ul>
        </div>

        <!-- MOVIES -->
        <div class="section">
            <h2>Movies</h2>
            <ul>
                {% for movie in movies %}
                <li>{{ movie["title"] }} {{ movie["description"] }}</li>
                {% endfor %}
            </ul>
        </div>

        <!-- SONGS -->
        <div class="section">
            <h2>Top Songs</h2>
            <ul>
                {% for song in songs %}
                <li>{{ song["title"] }} {{ song["description"] }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="footer">
        Generated by EDA-Archive • A glimpse into history
    </div>

</div>

</body>
</html>
"""

@celery.task
def generate_report(order_id):
    db = SessionLocal()
    order = db.query(Order).get(order_id)

    if not order:
        return

    # 1. Generate facts, movies, and songs
    facts = generate_facts(get_date_formatted(order.date)).get("headlines", [])
    movies = generate_movies(get_date_formatted(order.date)).get("movies", [])
    songs = generate_songs(get_date_formatted(order.date)).get("songs", [])
    prices = generate_prices(get_date_formatted(order.date)).get("item", [])

    # 2. Process image
    img = Image.open(order.image_path).convert("L")
    processed_path = f"{OUTPUT_DIR}/processed_{order_id}.png"
    img.save(processed_path)

    # 3. Generate QR (dummy Spotify link)
    qr_path = f"{OUTPUT_DIR}/spotify_qr_{order_id}.png"
    qrcode.make("https://spotify.com").save(qr_path)

    # 4. Render HTML
    html = Template(HTML_TEMPLATE).render(
        date=order.date,
        location=order.location,
        facts=facts,
        movies=movies,
        songs=songs,
        prices=prices,
        image=processed_path,
        qr=qr_path
    )

    # 5. Generate PDF
    pdf_path = f"{OUTPUT_DIR}/report_{order_id}.pdf"
    HTML(string=html).write_pdf(pdf_path)

    # 6. Save result
    order.pdf_path = pdf_path
    order.status = "done"
    db.commit()

    print(f"Report generated: {pdf_path}")